#include "modules/register_module_types.h"

void initialize_stable_diffusion_gd_module(ModuleInitializationLevel p_level);
void uninitialize_stable_diffusion_gd_module(ModuleInitializationLevel p_level);
